//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbAcademiaProgramadoresEntities2 : DbContext
    {
        public dbAcademiaProgramadoresEntities2()
            : base("name=dbAcademiaProgramadoresEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAlumnos> tbAlumnos { get; set; }
        public virtual DbSet<tbCategorias> tbCategorias { get; set; }
        public virtual DbSet<tbCursos> tbCursos { get; set; }
        public virtual DbSet<tbGeneraciones> tbGeneraciones { get; set; }
        public virtual DbSet<tbInstructores> tbInstructores { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbActividades> tbActividades { get; set; }
        public virtual DbSet<tbCentrosEducativos> tbCentrosEducativos { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbTitulos> tbTitulos { get; set; }
        public virtual DbSet<tbCalificaciones> tbCalificaciones { get; set; }
        public virtual DbSet<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracion { get; set; }
        public virtual DbSet<tbActividadesPorCursoPorGeneracion> tbActividadesPorCursoPorGeneracion { get; set; }
        public virtual DbSet<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
    
        public virtual int SP_tbUsuarios_DELETE(Nullable<int> usuar_Id, Nullable<int> usuar_UsuarioModificacion, Nullable<System.DateTime> usuar_FechaModificacion)
        {
            var usuar_IdParameter = usuar_Id.HasValue ?
                new ObjectParameter("Usuar_Id", usuar_Id) :
                new ObjectParameter("Usuar_Id", typeof(int));
    
            var usuar_UsuarioModificacionParameter = usuar_UsuarioModificacion.HasValue ?
                new ObjectParameter("Usuar_UsuarioModificacion", usuar_UsuarioModificacion) :
                new ObjectParameter("Usuar_UsuarioModificacion", typeof(int));
    
            var usuar_FechaModificacionParameter = usuar_FechaModificacion.HasValue ?
                new ObjectParameter("Usuar_FechaModificacion", usuar_FechaModificacion) :
                new ObjectParameter("Usuar_FechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_tbUsuarios_DELETE", usuar_IdParameter, usuar_UsuarioModificacionParameter, usuar_FechaModificacionParameter);
        }
    
        public virtual int SP_tbUsuarios_INSERT(string usuar_Usuario, string usuar_Contrasena, Nullable<int> instr_Id, Nullable<int> roles_Id, Nullable<bool> usuar_Admin, Nullable<int> usuar_UsuarioCreacion, Nullable<System.DateTime> usuar_FechaCreacion)
        {
            var usuar_UsuarioParameter = usuar_Usuario != null ?
                new ObjectParameter("Usuar_Usuario", usuar_Usuario) :
                new ObjectParameter("Usuar_Usuario", typeof(string));
    
            var usuar_ContrasenaParameter = usuar_Contrasena != null ?
                new ObjectParameter("Usuar_Contrasena", usuar_Contrasena) :
                new ObjectParameter("Usuar_Contrasena", typeof(string));
    
            var instr_IdParameter = instr_Id.HasValue ?
                new ObjectParameter("Instr_Id", instr_Id) :
                new ObjectParameter("Instr_Id", typeof(int));
    
            var roles_IdParameter = roles_Id.HasValue ?
                new ObjectParameter("Roles_Id", roles_Id) :
                new ObjectParameter("Roles_Id", typeof(int));
    
            var usuar_AdminParameter = usuar_Admin.HasValue ?
                new ObjectParameter("Usuar_Admin", usuar_Admin) :
                new ObjectParameter("Usuar_Admin", typeof(bool));
    
            var usuar_UsuarioCreacionParameter = usuar_UsuarioCreacion.HasValue ?
                new ObjectParameter("Usuar_UsuarioCreacion", usuar_UsuarioCreacion) :
                new ObjectParameter("Usuar_UsuarioCreacion", typeof(int));
    
            var usuar_FechaCreacionParameter = usuar_FechaCreacion.HasValue ?
                new ObjectParameter("Usuar_FechaCreacion", usuar_FechaCreacion) :
                new ObjectParameter("Usuar_FechaCreacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_tbUsuarios_INSERT", usuar_UsuarioParameter, usuar_ContrasenaParameter, instr_IdParameter, roles_IdParameter, usuar_AdminParameter, usuar_UsuarioCreacionParameter, usuar_FechaCreacionParameter);
        }
    
        public virtual int SP_tbUsuarios_UPDATE(Nullable<int> usuar_Id, string usuar_Usuario, string new_Usuar_Contrasena, Nullable<int> instr_Id, Nullable<int> roles_Id, Nullable<bool> usuar_Admin, Nullable<int> usuar_UsuarioModificacion, Nullable<System.DateTime> usuar_FechaModificacion)
        {
            var usuar_IdParameter = usuar_Id.HasValue ?
                new ObjectParameter("Usuar_Id", usuar_Id) :
                new ObjectParameter("Usuar_Id", typeof(int));
    
            var usuar_UsuarioParameter = usuar_Usuario != null ?
                new ObjectParameter("Usuar_Usuario", usuar_Usuario) :
                new ObjectParameter("Usuar_Usuario", typeof(string));
    
            var new_Usuar_ContrasenaParameter = new_Usuar_Contrasena != null ?
                new ObjectParameter("New_Usuar_Contrasena", new_Usuar_Contrasena) :
                new ObjectParameter("New_Usuar_Contrasena", typeof(string));
    
            var instr_IdParameter = instr_Id.HasValue ?
                new ObjectParameter("Instr_Id", instr_Id) :
                new ObjectParameter("Instr_Id", typeof(int));
    
            var roles_IdParameter = roles_Id.HasValue ?
                new ObjectParameter("Roles_Id", roles_Id) :
                new ObjectParameter("Roles_Id", typeof(int));
    
            var usuar_AdminParameter = usuar_Admin.HasValue ?
                new ObjectParameter("Usuar_Admin", usuar_Admin) :
                new ObjectParameter("Usuar_Admin", typeof(bool));
    
            var usuar_UsuarioModificacionParameter = usuar_UsuarioModificacion.HasValue ?
                new ObjectParameter("Usuar_UsuarioModificacion", usuar_UsuarioModificacion) :
                new ObjectParameter("Usuar_UsuarioModificacion", typeof(int));
    
            var usuar_FechaModificacionParameter = usuar_FechaModificacion.HasValue ?
                new ObjectParameter("Usuar_FechaModificacion", usuar_FechaModificacion) :
                new ObjectParameter("Usuar_FechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_tbUsuarios_UPDATE", usuar_IdParameter, usuar_UsuarioParameter, new_Usuar_ContrasenaParameter, instr_IdParameter, roles_IdParameter, usuar_AdminParameter, usuar_UsuarioModificacionParameter, usuar_FechaModificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_PantallasPorRoles_InsertarEliminar(string panta_IdsXML, Nullable<int> roles_Id, Nullable<int> papro_UsuarioCreacion, Nullable<System.DateTime> papro_FechaCreacion)
        {
            var panta_IdsXMLParameter = panta_IdsXML != null ?
                new ObjectParameter("Panta_IdsXML", panta_IdsXML) :
                new ObjectParameter("Panta_IdsXML", typeof(string));
    
            var roles_IdParameter = roles_Id.HasValue ?
                new ObjectParameter("Roles_Id", roles_Id) :
                new ObjectParameter("Roles_Id", typeof(int));
    
            var papro_UsuarioCreacionParameter = papro_UsuarioCreacion.HasValue ?
                new ObjectParameter("Papro_UsuarioCreacion", papro_UsuarioCreacion) :
                new ObjectParameter("Papro_UsuarioCreacion", typeof(int));
    
            var papro_FechaCreacionParameter = papro_FechaCreacion.HasValue ?
                new ObjectParameter("Papro_FechaCreacion", papro_FechaCreacion) :
                new ObjectParameter("Papro_FechaCreacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_PantallasPorRoles_InsertarEliminar", panta_IdsXMLParameter, roles_IdParameter, papro_UsuarioCreacionParameter, papro_FechaCreacionParameter);
        }
    
        public virtual ObjectResult<SP_Usuarios_Login_Result> SP_Usuarios_Login(string usuario, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Usuarios_Login_Result>("SP_Usuarios_Login", usuarioParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<SP_PantallasPorRoles_SeleccionarRolesPorPantalla_Result> SP_PantallasPorRoles_SeleccionarRolesPorPantalla(string panta_Descripcion)
        {
            var panta_DescripcionParameter = panta_Descripcion != null ?
                new ObjectParameter("Panta_Descripcion", panta_Descripcion) :
                new ObjectParameter("Panta_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PantallasPorRoles_SeleccionarRolesPorPantalla_Result>("SP_PantallasPorRoles_SeleccionarRolesPorPantalla", panta_DescripcionParameter);
        }
    
        public virtual ObjectResult<SP_PantallasPorRoles_SeleccionarPantallasPorRol_Result> SP_PantallasPorRoles_SeleccionarPantallasPorRol(Nullable<int> roles_Id)
        {
            var roles_IdParameter = roles_Id.HasValue ?
                new ObjectParameter("Roles_Id", roles_Id) :
                new ObjectParameter("Roles_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PantallasPorRoles_SeleccionarPantallasPorRol_Result>("SP_PantallasPorRoles_SeleccionarPantallasPorRol", roles_IdParameter);
        }
    
        public virtual ObjectResult<SP_Departamentos_LlenarEditar_Result> SP_Departamentos_LlenarEditar(string depar_Id)
        {
            var depar_IdParameter = depar_Id != null ?
                new ObjectParameter("Depar_Id", depar_Id) :
                new ObjectParameter("Depar_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Departamentos_LlenarEditar_Result>("SP_Departamentos_LlenarEditar", depar_IdParameter);
        }
    
        public virtual ObjectResult<SP_EstadosCiviles_LlenarEditar_Result> SP_EstadosCiviles_LlenarEditar(Nullable<int> estci_Id)
        {
            var estci_IdParameter = estci_Id.HasValue ?
                new ObjectParameter("Estci_Id", estci_Id) :
                new ObjectParameter("Estci_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EstadosCiviles_LlenarEditar_Result>("SP_EstadosCiviles_LlenarEditar", estci_IdParameter);
        }
    
        public virtual ObjectResult<SP_Municipios_LlenarEditar_Result> SP_Municipios_LlenarEditar(string munic_Id)
        {
            var munic_IdParameter = munic_Id != null ?
                new ObjectParameter("Munic_Id", munic_Id) :
                new ObjectParameter("Munic_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Municipios_LlenarEditar_Result>("SP_Municipios_LlenarEditar", munic_IdParameter);
        }
    
        public virtual ObjectResult<SP_Titulos_DropDownList_Result> SP_Titulos_DropDownList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Titulos_DropDownList_Result>("SP_Titulos_DropDownList");
        }
    
        public virtual ObjectResult<SP_Titulos_LlenarEditar_Result> SP_Titulos_LlenarEditar(Nullable<int> titul_Id)
        {
            var titul_IdParameter = titul_Id.HasValue ?
                new ObjectParameter("Titul_Id", titul_Id) :
                new ObjectParameter("Titul_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Titulos_LlenarEditar_Result>("SP_Titulos_LlenarEditar", titul_IdParameter);
        }
    
        public virtual ObjectResult<SP_InstructoresPorCursoPorGeneracion_Seleccionar_Result> SP_InstructoresPorCursoPorGeneracion_Seleccionar(Nullable<int> instr_Id, Nullable<int> gener_Id)
        {
            var instr_IdParameter = instr_Id.HasValue ?
                new ObjectParameter("Instr_Id", instr_Id) :
                new ObjectParameter("Instr_Id", typeof(int));
    
            var gener_IdParameter = gener_Id.HasValue ?
                new ObjectParameter("Gener_Id", gener_Id) :
                new ObjectParameter("Gener_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InstructoresPorCursoPorGeneracion_Seleccionar_Result>("SP_InstructoresPorCursoPorGeneracion_Seleccionar", instr_IdParameter, gener_IdParameter);
        }
    
        public virtual int SP_Calificaciones_Seleccionar(Nullable<int> curso_Id, Nullable<int> gener_Id)
        {
            var curso_IdParameter = curso_Id.HasValue ?
                new ObjectParameter("Curso_Id", curso_Id) :
                new ObjectParameter("Curso_Id", typeof(int));
    
            var gener_IdParameter = gener_Id.HasValue ?
                new ObjectParameter("Gener_Id", gener_Id) :
                new ObjectParameter("Gener_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Calificaciones_Seleccionar", curso_IdParameter, gener_IdParameter);
        }
    
        public virtual ObjectResult<SP_ActividadesPorCursoPorGeneracion_Seleccionar_Result> SP_ActividadesPorCursoPorGeneracion_Seleccionar(Nullable<int> curso_Id, Nullable<int> gener_Id)
        {
            var curso_IdParameter = curso_Id.HasValue ?
                new ObjectParameter("Curso_Id", curso_Id) :
                new ObjectParameter("Curso_Id", typeof(int));
    
            var gener_IdParameter = gener_Id.HasValue ?
                new ObjectParameter("Gener_Id", gener_Id) :
                new ObjectParameter("Gener_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ActividadesPorCursoPorGeneracion_Seleccionar_Result>("SP_ActividadesPorCursoPorGeneracion_Seleccionar", curso_IdParameter, gener_IdParameter);
        }
    
        public virtual ObjectResult<SP_Calificaciones2_Seleccionar_Result> SP_Calificaciones2_Seleccionar(Nullable<int> curso_Id, Nullable<int> gener_Id)
        {
            var curso_IdParameter = curso_Id.HasValue ?
                new ObjectParameter("Curso_Id", curso_Id) :
                new ObjectParameter("Curso_Id", typeof(int));
    
            var gener_IdParameter = gener_Id.HasValue ?
                new ObjectParameter("Gener_Id", gener_Id) :
                new ObjectParameter("Gener_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Calificaciones2_Seleccionar_Result>("SP_Calificaciones2_Seleccionar", curso_IdParameter, gener_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Calificaciones_Modificar(string actCG_Id, string alumn_Id, Nullable<decimal> calif_Nota, string calif_UsuarioModificacion, Nullable<System.DateTime> calif_FechaModificacion)
        {
            var actCG_IdParameter = actCG_Id != null ?
                new ObjectParameter("ActCG_Id", actCG_Id) :
                new ObjectParameter("ActCG_Id", typeof(string));
    
            var alumn_IdParameter = alumn_Id != null ?
                new ObjectParameter("Alumn_Id", alumn_Id) :
                new ObjectParameter("Alumn_Id", typeof(string));
    
            var calif_NotaParameter = calif_Nota.HasValue ?
                new ObjectParameter("Calif_Nota", calif_Nota) :
                new ObjectParameter("Calif_Nota", typeof(decimal));
    
            var calif_UsuarioModificacionParameter = calif_UsuarioModificacion != null ?
                new ObjectParameter("Calif_UsuarioModificacion", calif_UsuarioModificacion) :
                new ObjectParameter("Calif_UsuarioModificacion", typeof(string));
    
            var calif_FechaModificacionParameter = calif_FechaModificacion.HasValue ?
                new ObjectParameter("Calif_FechaModificacion", calif_FechaModificacion) :
                new ObjectParameter("Calif_FechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Calificaciones_Modificar", actCG_IdParameter, alumn_IdParameter, calif_NotaParameter, calif_UsuarioModificacionParameter, calif_FechaModificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Calificaciones_Insertar(string actCG_Id, string alumn_Id, Nullable<decimal> calif_Nota, string calif_UsuarioCreacion, Nullable<System.DateTime> calif_FechaCreacion)
        {
            var actCG_IdParameter = actCG_Id != null ?
                new ObjectParameter("ActCG_Id", actCG_Id) :
                new ObjectParameter("ActCG_Id", typeof(string));
    
            var alumn_IdParameter = alumn_Id != null ?
                new ObjectParameter("Alumn_Id", alumn_Id) :
                new ObjectParameter("Alumn_Id", typeof(string));
    
            var calif_NotaParameter = calif_Nota.HasValue ?
                new ObjectParameter("Calif_Nota", calif_Nota) :
                new ObjectParameter("Calif_Nota", typeof(decimal));
    
            var calif_UsuarioCreacionParameter = calif_UsuarioCreacion != null ?
                new ObjectParameter("Calif_UsuarioCreacion", calif_UsuarioCreacion) :
                new ObjectParameter("Calif_UsuarioCreacion", typeof(string));
    
            var calif_FechaCreacionParameter = calif_FechaCreacion.HasValue ?
                new ObjectParameter("Calif_FechaCreacion", calif_FechaCreacion) :
                new ObjectParameter("Calif_FechaCreacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Calificaciones_Insertar", actCG_IdParameter, alumn_IdParameter, calif_NotaParameter, calif_UsuarioCreacionParameter, calif_FechaCreacionParameter);
        }
    }
}
