//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividadesPorCursoPorGeneracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbActividadesPorCursoPorGeneracion()
        {
            this.tbCalificaciones = new HashSet<tbCalificaciones>();
        }
    
        public int ActCG_Id { get; set; }
        public int Activ_Id { get; set; }
        public int InsCG_Id { get; set; }
        public decimal ActCG_Nota { get; set; }
        public int ActCG_UsuarioCreacion { get; set; }
        public System.DateTime ActCG_FechaCreacion { get; set; }
        public Nullable<int> ActCG_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> ActCG_FechaModificacion { get; set; }
    
        public virtual tbInstructoresPorCursoPorGeneracion tbInstructoresPorCursoPorGeneracion { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbActividades tbActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCalificaciones> tbCalificaciones { get; set; }
    }
}
