//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCategorias()
        {
            this.tbCursos = new HashSet<tbCursos>();
        }
    
        public int Categ_Id { get; set; }
        public string Categ_Nombre { get; set; }
        public int Categ_UsuarioCreacion { get; set; }
        public System.DateTime Categ_FechaCreacion { get; set; }
        public Nullable<int> Categ_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Categ_FechaModificacion { get; set; }
        public bool Categ_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCursos> tbCursos { get; set; }
    }
}
