//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCentrosEducativos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCentrosEducativos()
        {
            this.tbAlumnos = new HashSet<tbAlumnos>();
            this.tbAlumnos1 = new HashSet<tbAlumnos>();
            this.tbInstructores = new HashSet<tbInstructores>();
        }
    
        public int CenEd_Id { get; set; }
        public string CenEd_Nombre { get; set; }
        public string CenEd_Direccion { get; set; }
        public string CenEd_Tipo { get; set; }
        public string Munic_Id { get; set; }
        public int CenEd_UsuarioCreacion { get; set; }
        public System.DateTime CenEd_FechaCreacion { get; set; }
        public Nullable<int> CenEd_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> CenEd_FechaModificacion { get; set; }
        public bool CenEd_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAlumnos> tbAlumnos1 { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructores> tbInstructores { get; set; }
    }
}
