//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCursos()
        {
            this.tbInstructoresPorCursoPorGeneracion = new HashSet<tbInstructoresPorCursoPorGeneracion>();
        }
    
        public int Curso_Id { get; set; }
        public string Curso_Nombre { get; set; }
        public int Categ_Id { get; set; }
        public int Curso_UsuarioCreacion { get; set; }
        public System.DateTime Curso_FechaCreacion { get; set; }
        public Nullable<int> Curso_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Curso_FechaModificacion { get; set; }
        public bool Curso_Estado { get; set; }
    
        public virtual tbCategorias tbCategorias { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracion { get; set; }
    }
}
