//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAcademiaProgramadoresEntities : DbContext
    {
        public dbAcademiaProgramadoresEntities()
            : base("name=dbAcademiaProgramadoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAlumno> tbAlumnos { get; set; }
        public virtual DbSet<tbCurso> tbCursos { get; set; }
        public virtual DbSet<tbCursosPorGeneracion> tbCursosPorGeneracions { get; set; }
        public virtual DbSet<tbGeneracione> tbGeneraciones { get; set; }
        public virtual DbSet<tbInstructore> tbInstructores { get; set; }
        public virtual DbSet<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracions { get; set; }
        public virtual DbSet<tbPantalla> tbPantallas { get; set; }
        public virtual DbSet<tbPantallasPorRole> tbPantallasPorRoles { get; set; }
        public virtual DbSet<tbRole> tbRoles { get; set; }
        public virtual DbSet<tbUsuario> tbUsuarios { get; set; }
        public virtual DbSet<tbActividade> tbActividades { get; set; }
        public virtual DbSet<tbActividadesPorCursoPorGeneracion> tbActividadesPorCursoPorGeneracions { get; set; }
        public virtual DbSet<tbCalificacione> tbCalificaciones { get; set; }
        public virtual DbSet<tbDepartamento> tbDepartamentos { get; set; }
        public virtual DbSet<tbEstadosCivile> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbMunicipio> tbMunicipios { get; set; }
        public virtual DbSet<tbPersona> tbPersonas { get; set; }
    }
}
