//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    
    public partial class SP_CentrosEducativos_DropDownListTipo_Result1
    {
        public string CenEd_Tipo { get; set; }
        public string CenEd_TipoDescripcion { get; set; }
    }
}
