//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    
    public partial class SP_Calificaciones2_Seleccionar_Result1
    {
        public int Perso_Id { get; set; }
        public string ALUMNO { get; set; }
        public int ActCG_Id { get; set; }
        public int Calif_Id { get; set; }
        public decimal Calif_Nota { get; set; }
    }
}
