//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    
    public partial class SP_tbUsuarios_LOGIN_Result1
    {
        public int Usuar_Id { get; set; }
        public string Usuar_Usuario { get; set; }
        public string Usuar_Contrasena { get; set; }
        public string Perso_NombreCompleto { get; set; }
        public int Perso_Id { get; set; }
        public string Perso_PrimerNombre { get; set; }
        public string Perso_SegundoNombre { get; set; }
        public string Perso_PrimerApellido { get; set; }
        public string Perso_SegundoApellido { get; set; }
        public System.DateTime Perso_FechaNacimiento { get; set; }
        public string Perso_Sexo { get; set; }
        public int Estci_Id { get; set; }
        public string Perso_Direccion { get; set; }
        public string Munic_Id { get; set; }
        public string Perso_Telefono { get; set; }
        public string Perso_CorreoElectronico { get; set; }
        public int Perso_UsuarioCreacion { get; set; }
        public System.DateTime Perso_FechaCreacion { get; set; }
        public Nullable<int> Perso_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Perso_FechaModificacion { get; set; }
        public bool Perso_Estado { get; set; }
    }
}
