//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividadesPorCursoPorGeneracion
    {
        public int ActCG_Id { get; set; }
        public int Activ_Id { get; set; }
        public int CuGen_Id { get; set; }
        public decimal ActCG_Nota { get; set; }
        public int ActCG_UsuarioCreacion { get; set; }
        public System.DateTime ActCG_FechaCreacion { get; set; }
        public Nullable<int> ActCG_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> ActCG_FechaModificacion { get; set; }
        public Nullable<bool> ActCG_Estado { get; set; }
    
        public virtual tbCursosPorGeneracion tbCursosPorGeneracion { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbActividades tbActividades { get; set; }
    }
}
