//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividade
    {
        public tbActividade()
        {
            this.tbActividadesPorCursoPorGeneracions = new HashSet<tbActividadesPorCursoPorGeneracion>();
        }
    
        public int Activ_Id { get; set; }
        public string Activ_Nombre { get; set; }
        public int Activ_UsuarioCreacion { get; set; }
        public System.DateTime Activ_FechaCreacion { get; set; }
        public Nullable<int> Activ_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Activ_FechaModificacion { get; set; }
        public Nullable<bool> Activ_Estado { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual ICollection<tbActividadesPorCursoPorGeneracion> tbActividadesPorCursoPorGeneracions { get; set; }
    }
}
