//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividadesPorCursoPorGeneracion
    {
        public int ActCG_Id { get; set; }
        public int Activ_Id { get; set; }
        public int CuGen_Id { get; set; }
        public decimal ActCG_Nota { get; set; }
        public int ActCG_UsuarioCreacion { get; set; }
        public System.DateTime ActCG_FechaCreacion { get; set; }
        public Nullable<int> ActCG_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> ActCG_FechaModificacion { get; set; }
        public bool ActCG_Estado { get; set; }
    
        public virtual tbCursosPorGeneracion tbCursosPorGeneracion { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbActividades tbActividades { get; set; }
    }
}
