//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAlumnos()
        {
            this.tbCalificaciones = new HashSet<tbCalificaciones>();
        }
    
        public int Perso_Id { get; set; }
        public int CenEd_IdColegio { get; set; }
        public int CenEd_IdUniversidad { get; set; }
        public int Titul_Id { get; set; }
        public int Gener_Id { get; set; }
        public int Alumn_UsuarioCreacion { get; set; }
        public System.DateTime Alumn_FechaCreacion { get; set; }
        public Nullable<int> Alumn_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Alumn_FechaModificacion { get; set; }
        public bool Alumn_Estado { get; set; }
        public string Alumn_Observaciones { get; set; }
        public System.DateTime Alumn_FechaIngreso { get; set; }
    
        public virtual tbCentrosEducativos tbCentrosEducativos { get; set; }
        public virtual tbCentrosEducativos tbCentrosEducativos1 { get; set; }
        public virtual tbPersonas tbPersonas { get; set; }
        public virtual tbTitulos tbTitulos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCalificaciones> tbCalificaciones { get; set; }
    }
}
