//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlumno
    {
        public tbAlumno()
        {
            this.tbCalificaciones = new HashSet<tbCalificacione>();
        }
    
        public int Perso_Id { get; set; }
        public string Alumn_ColegioEgresion { get; set; }
        public string Alumn_Universidad { get; set; }
        public string Alumn_Telefono { get; set; }
        public string Alumn_CorreoElectronico { get; set; }
        public string Alumn_TituloEgresion { get; set; }
        public int Alumn_UsuarioCreacion { get; set; }
        public System.DateTime Alumn_FechaCreacion { get; set; }
        public Nullable<int> Alumn_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Alumn_FechaModificacion { get; set; }
        public Nullable<bool> Alumn_Estado { get; set; }
    
        public virtual tbPersona tbPersona { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual ICollection<tbCalificacione> tbCalificaciones { get; set; }
    }
}
