//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlumnosBitacora
    {
        public Nullable<int> Perso_Id { get; set; }
        public Nullable<int> CenEd_IdColegio { get; set; }
        public Nullable<int> CenEd_IdUniversidad { get; set; }
        public Nullable<int> Titul_Id { get; set; }
        public Nullable<int> Alumn_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> Alumn_FechaCreacion { get; set; }
        public Nullable<int> Alumn_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Alumn_FechaModificacion { get; set; }
        public Nullable<bool> Alumn_Estado { get; set; }
        public string Alumn_Observaciones { get; set; }
        public Nullable<System.DateTime> Alumn_FechaIngreso { get; set; }
        public string AlBit_Accion { get; set; }
        public Nullable<System.DateTime> AlBit_FechaAccion { get; set; }
    }
}
