//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCategorias()
        {
            this.tbCursos = new HashSet<tbCursos>();
        }
    
        public int Categ_Id { get; set; }
        public string Categ_Nombre { get; set; }
        public int Categ_UsuarioCreacion { get; set; }
        public System.DateTime Categ_FechaCreacion { get; set; }
        public Nullable<int> Categ_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Categ_FechaModificacion { get; set; }
        public bool Categ_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCursos> tbCursos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
