//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCalificaciones
    {
        public int Calif_Id { get; set; }
        public int CuGen_Id { get; set; }
        public int Alumn_Id { get; set; }
        public decimal Calif_Nota { get; set; }
        public int Calif_UsuarioCreacion { get; set; }
        public System.DateTime Calif_FechaCreacion { get; set; }
        public Nullable<int> Calif_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Calif_FechaModificacion { get; set; }
        public bool Calif_Estado { get; set; }
    
        public virtual tbAlumnos tbAlumnos { get; set; }
        public virtual tbCursosPorGeneracion tbCursosPorGeneracion { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
