//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCursos()
        {
            this.tbCursosPorGeneracion = new HashSet<tbCursosPorGeneracion>();
        }
    
        public int Curso_Id { get; set; }
        public string Curso_Nombre { get; set; }
        public int Categ_Id { get; set; }
        public int Curso_UsuarioCreacion { get; set; }
        public System.DateTime Curso_FechaCreacion { get; set; }
        public Nullable<int> Curso_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Curso_FechaModificacion { get; set; }
        public bool Curso_Estado { get; set; }
    
        public virtual tbCategorias tbCategorias { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCursosPorGeneracion> tbCursosPorGeneracion { get; set; }
    }
}
