//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCursosPorGeneracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCursosPorGeneracion()
        {
            this.tbActividadesPorCursoPorGeneracion = new HashSet<tbActividadesPorCursoPorGeneracion>();
            this.tbCalificaciones = new HashSet<tbCalificaciones>();
            this.tbInstructoresPorCursoPorGeneracion = new HashSet<tbInstructoresPorCursoPorGeneracion>();
        }
    
        public int CuGen_Id { get; set; }
        public int Curso_Id { get; set; }
        public int Gener_Id { get; set; }
        public int CuGen_UsuarioCreacion { get; set; }
        public System.DateTime CuGen_FechaCreacion { get; set; }
        public Nullable<int> CuGen_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> CuGen_FechaModificacion { get; set; }
        public bool CuGen_Estado { get; set; }
    
        public virtual tbCursos tbCursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActividadesPorCursoPorGeneracion> tbActividadesPorCursoPorGeneracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCalificaciones> tbCalificaciones { get; set; }
        public virtual tbGeneraciones tbGeneraciones { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracion { get; set; }
    }
}
