//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCurso
    {
        public tbCurso()
        {
            this.tbCursosPorGeneracions = new HashSet<tbCursosPorGeneracion>();
        }
    
        public int Curso_Id { get; set; }
        public string Curso_Nombre { get; set; }
        public int Curso_UsuarioCreacion { get; set; }
        public System.DateTime Curso_FechaCreacion { get; set; }
        public Nullable<int> Curso_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Curso_FechaModificacion { get; set; }
        public Nullable<bool> Curso_Estado { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual ICollection<tbCursosPorGeneracion> tbCursosPorGeneracions { get; set; }
    }
}
