//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCursosPorGeneracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCursosPorGeneracion()
        {
            this.tbActividadesPorCursoPorGeneracions = new HashSet<tbActividadesPorCursoPorGeneracion>();
            this.tbCalificaciones = new HashSet<tbCalificacione>();
            this.tbInstructoresPorCursoPorGeneracions = new HashSet<tbInstructoresPorCursoPorGeneracion>();
        }
    
        public int CuGen_Id { get; set; }
        public int Curso_Id { get; set; }
        public int Gener_Id { get; set; }
        public int CuGen_UsuarioCreacion { get; set; }
        public System.DateTime CuGen_FechaCreacion { get; set; }
        public Nullable<int> CuGen_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> CuGen_FechaModificacion { get; set; }
        public Nullable<bool> CuGen_Estado { get; set; }
    
        public virtual tbCurso tbCurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActividadesPorCursoPorGeneracion> tbActividadesPorCursoPorGeneracions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCalificacione> tbCalificaciones { get; set; }
        public virtual tbGeneracione tbGeneracione { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracions { get; set; }
    }
}
