//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamento
    {
        public tbDepartamento()
        {
            this.tbMunicipios = new HashSet<tbMunicipio>();
        }
    
        public string Depar_Id { get; set; }
        public string Depar_Descripcion { get; set; }
        public int Depar_UsuarioCreacion { get; set; }
        public System.DateTime Depar_FechaCreacion { get; set; }
        public Nullable<int> Depar_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Depar_FechaModificacion { get; set; }
        public Nullable<bool> Depar_Estado { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual ICollection<tbMunicipio> tbMunicipios { get; set; }
    }
}
