//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstadosCivile
    {
        public tbEstadosCivile()
        {
            this.tbPersonas = new HashSet<tbPersona>();
        }
    
        public int Estci_Id { get; set; }
        public string Estci_Descripcion { get; set; }
        public int Estci_UsuarioCreacion { get; set; }
        public System.DateTime Estci_FechaCreacion { get; set; }
        public Nullable<int> Estci_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Estci_FechaModificacion { get; set; }
        public Nullable<bool> Estci_Estado { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual ICollection<tbPersona> tbPersonas { get; set; }
    }
}
