//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGeneracione
    {
        public tbGeneracione()
        {
            this.tbCursosPorGeneracions = new HashSet<tbCursosPorGeneracion>();
        }
    
        public int Gener_Id { get; set; }
        public string Gener_Nombre { get; set; }
        public int Gener_Anhio { get; set; }
        public int Gener_UsuarioCreacion { get; set; }
        public System.DateTime Gener_FechaCreacion { get; set; }
        public Nullable<int> Gener_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Gener_FechaModificacion { get; set; }
        public Nullable<bool> Gener_Estado { get; set; }
    
        public virtual ICollection<tbCursosPorGeneracion> tbCursosPorGeneracions { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
