//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGeneraciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbGeneraciones()
        {
            this.tbInstructoresPorCursoPorGeneracion = new HashSet<tbInstructoresPorCursoPorGeneracion>();
        }
    
        public int Gener_Id { get; set; }
        public string Gener_Nombre { get; set; }
        public int Gener_Anhio { get; set; }
        public int Gener_UsuarioCreacion { get; set; }
        public System.DateTime Gener_FechaCreacion { get; set; }
        public Nullable<int> Gener_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Gener_FechaModificacion { get; set; }
        public bool Gener_Estado { get; set; }
        public System.DateTime Gener_FechaInicio { get; set; }
        public Nullable<System.DateTime> Gener_FechaFin { get; set; }
        public decimal Gener_Puntaje { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracion { get; set; }
    }
}
