//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstructoresPorCursoPorGeneracion
    {
        public int InsCG_Id { get; set; }
        public int Instr_Id { get; set; }
        public int CuGen_Id { get; set; }
        public int InsCG_UsuarioCreacion { get; set; }
        public System.DateTime InsCG_FechaCreacion { get; set; }
        public Nullable<int> InsCG_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> InsCG_FechaModificacion { get; set; }
        public Nullable<bool> InsCG_Estado { get; set; }
    
        public virtual tbCursosPorGeneracion tbCursosPorGeneracion { get; set; }
        public virtual tbInstructore tbInstructore { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
