//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstructores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbInstructores()
        {
            this.tbInstructoresPorCursoPorGeneracion = new HashSet<tbInstructoresPorCursoPorGeneracion>();
            this.tbUsuarios2 = new HashSet<tbUsuarios>();
        }
    
        public int Perso_Id { get; set; }
        public int Titul_Id { get; set; }
        public int CenEd_Id { get; set; }
        public int Instr_UsuarioCreacion { get; set; }
        public System.DateTime Instr_FechaCreacion { get; set; }
        public Nullable<int> Instr_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Instr_FechaModificacion { get; set; }
        public bool Instr_Estado { get; set; }
    
        public virtual tbPersonas tbPersonas { get; set; }
        public virtual tbTitulos tbTitulos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios2 { get; set; }
    }
}
