//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstructores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbInstructores()
        {
            this.tbUsuarios2 = new HashSet<tbUsuarios>();
            this.tbInstructoresPorCursoPorGeneracion = new HashSet<tbInstructoresPorCursoPorGeneracion>();
        }
    
        public int Perso_Id { get; set; }
        public int Titul_Id { get; set; }
        public int CenEd_Id { get; set; }
        public int Instr_UsuarioCreacion { get; set; }
        public System.DateTime Instr_FechaCreacion { get; set; }
        public Nullable<int> Instr_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Instr_FechaModificacion { get; set; }
        public bool Instr_Estado { get; set; }
    
        public virtual tbPersonas tbPersonas { get; set; }
        public virtual tbTitulos tbTitulos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracion { get; set; }
        public virtual tbCentrosEducativos tbCentrosEducativos { get; set; }
    }
}
