//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstructore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbInstructore()
        {
            this.tbInstructoresPorCursoPorGeneracions = new HashSet<tbInstructoresPorCursoPorGeneracion>();
            this.tbUsuarios = new HashSet<tbUsuario>();
        }
    
        public int Perso_Id { get; set; }
        public string Instr_Telefono { get; set; }
        public string Instr_CorreoElectronico { get; set; }
        public string Instr_Pregrado { get; set; }
        public string Instr_Posgrado { get; set; }
        public int Instr_UsuarioCreacion { get; set; }
        public System.DateTime Instr_FechaCreacion { get; set; }
        public Nullable<int> Instr_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Instr_FechaModificacion { get; set; }
        public Nullable<bool> Instr_Estado { get; set; }
    
        public virtual tbPersona tbPersona { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuario> tbUsuarios { get; set; }
    }
}
