//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstructoresPorCursoPorGeneracion
    {
        public int InsCG_Id { get; set; }
        public int Instr_Id { get; set; }
        public int CuGen_Id { get; set; }
        public int InsCG_UsuarioCreacion { get; set; }
        public System.DateTime InsCG_FechaCreacion { get; set; }
        public Nullable<int> InsCG_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> InsCG_FechaModificacion { get; set; }
        public bool InsCG_Estado { get; set; }
    
        public virtual tbCursosPorGeneracion tbCursosPorGeneracion { get; set; }
        public virtual tbInstructores tbInstructores { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
