//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPantallasPorRoles
    {
        public int Papro_Id { get; set; }
        public int Panta_Id { get; set; }
        public int Roles_Id { get; set; }
        public int Papro_UsuarioCreacion { get; set; }
        public System.DateTime Papro_FechaCreacion { get; set; }
        public Nullable<int> Papro_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Papro_FechaModificacion { get; set; }
        public bool Papro_Estado { get; set; }
    
        public virtual tbPantallas tbPantallas { get; set; }
        public virtual tbRoles tbRoles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
