//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPantallasPorRole
    {
        public int Papro_Id { get; set; }
        public int Panta_Id { get; set; }
        public int Roles_Id { get; set; }
        public int Papro_UsuarioCreacion { get; set; }
        public System.DateTime Papro_FechaCreacion { get; set; }
        public Nullable<int> Papro_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Papro_FechaModificacion { get; set; }
        public Nullable<bool> Papro_Estado { get; set; }
    
        public virtual tbPantalla tbPantalla { get; set; }
        public virtual tbRole tbRole { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
