//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTitulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTitulos()
        {
            this.tbAlumnos = new HashSet<tbAlumnos>();
            this.tbInstructores = new HashSet<tbInstructores>();
        }
    
        public int Titul_Id { get; set; }
        public string Titul_Nombre { get; set; }
        public string Titul_Tipo { get; set; }
        public int Titul_UsuarioCreacion { get; set; }
        public System.DateTime Titul_FechaCreacion { get; set; }
        public Nullable<int> Titul_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Titul_FechaModificacion { get; set; }
        public bool Titul_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructores> tbInstructores { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
