//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademiaProgramadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsuario()
        {
            this.tbAlumnos = new HashSet<tbAlumno>();
            this.tbAlumnos1 = new HashSet<tbAlumno>();
            this.tbCursos = new HashSet<tbCurso>();
            this.tbCursos1 = new HashSet<tbCurso>();
            this.tbCursosPorGeneracions = new HashSet<tbCursosPorGeneracion>();
            this.tbCursosPorGeneracions1 = new HashSet<tbCursosPorGeneracion>();
            this.tbGeneraciones = new HashSet<tbGeneracione>();
            this.tbGeneraciones1 = new HashSet<tbGeneracione>();
            this.tbInstructores = new HashSet<tbInstructore>();
            this.tbInstructores1 = new HashSet<tbInstructore>();
            this.tbInstructoresPorCursoPorGeneracions = new HashSet<tbInstructoresPorCursoPorGeneracion>();
            this.tbInstructoresPorCursoPorGeneracions1 = new HashSet<tbInstructoresPorCursoPorGeneracion>();
            this.tbPantallas = new HashSet<tbPantalla>();
            this.tbPantallas1 = new HashSet<tbPantalla>();
            this.tbPantallasPorRoles = new HashSet<tbPantallasPorRole>();
            this.tbPantallasPorRoles1 = new HashSet<tbPantallasPorRole>();
            this.tbActividades = new HashSet<tbActividade>();
            this.tbActividades1 = new HashSet<tbActividade>();
            this.tbActividadesPorCursoPorGeneracions = new HashSet<tbActividadesPorCursoPorGeneracion>();
            this.tbActividadesPorCursoPorGeneracions1 = new HashSet<tbActividadesPorCursoPorGeneracion>();
            this.tbCalificaciones = new HashSet<tbCalificacione>();
            this.tbCalificaciones1 = new HashSet<tbCalificacione>();
            this.tbDepartamentos = new HashSet<tbDepartamento>();
            this.tbDepartamentos1 = new HashSet<tbDepartamento>();
            this.tbEstadosCiviles = new HashSet<tbEstadosCivile>();
            this.tbEstadosCiviles1 = new HashSet<tbEstadosCivile>();
            this.tbMunicipios = new HashSet<tbMunicipio>();
            this.tbMunicipios1 = new HashSet<tbMunicipio>();
            this.tbPersonas = new HashSet<tbPersona>();
            this.tbPersonas1 = new HashSet<tbPersona>();
            this.tbUsuarios1 = new HashSet<tbUsuario>();
            this.tbUsuarios11 = new HashSet<tbUsuario>();
        }
    
        public int Usuar_Id { get; set; }
        public string Usuar_Usuario { get; set; }
        public string Usuar_Contrasena { get; set; }
        public string Usuar_Correo { get; set; }
        public Nullable<System.DateTime> Usuar_UltimaSesion { get; set; }
        public int Instr_Id { get; set; }
        public int Roles_Id { get; set; }
        public Nullable<bool> Usuar_Admin { get; set; }
        public int Usuar_UsuarioCreacion { get; set; }
        public System.DateTime Usuar_FechaCreacion { get; set; }
        public Nullable<int> Usuar_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Usuar_FechaModificacion { get; set; }
        public Nullable<bool> Usuar_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAlumno> tbAlumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAlumno> tbAlumnos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCurso> tbCursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCurso> tbCursos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCursosPorGeneracion> tbCursosPorGeneracions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCursosPorGeneracion> tbCursosPorGeneracions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbGeneracione> tbGeneraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbGeneracione> tbGeneraciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructore> tbInstructores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructore> tbInstructores1 { get; set; }
        public virtual tbInstructore tbInstructore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInstructoresPorCursoPorGeneracion> tbInstructoresPorCursoPorGeneracions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPantalla> tbPantallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPantalla> tbPantallas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPantallasPorRole> tbPantallasPorRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPantallasPorRole> tbPantallasPorRoles1 { get; set; }
        public virtual tbRole tbRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActividade> tbActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActividade> tbActividades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActividadesPorCursoPorGeneracion> tbActividadesPorCursoPorGeneracions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActividadesPorCursoPorGeneracion> tbActividadesPorCursoPorGeneracions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCalificacione> tbCalificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCalificacione> tbCalificaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDepartamento> tbDepartamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDepartamento> tbDepartamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEstadosCivile> tbEstadosCiviles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEstadosCivile> tbEstadosCiviles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMunicipio> tbMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMunicipio> tbMunicipios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPersona> tbPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPersona> tbPersonas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuario> tbUsuarios1 { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuario> tbUsuarios11 { get; set; }
        public virtual tbUsuario tbUsuario2 { get; set; }
    }
}
